name: Splittermond CI

on:
  pull_request:
    branches:
      - main
      - devV*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Typecheck
        run: npm run typecheck
      - name: Run tests
        run: npm run test